### ISSUE TITLE
General comments and advice

### ISSUE THREAD

**Issue by AnneClaireH** [QCTW/ParisVII_ProjectMachineLearning#1]
That's a great start!

I do have 2 advices:
1. Focus on 1 single language first. I'd start with English, so maybe you should replace Macron/Mélenchon by english-speaking celebrities. 2 reasons: a/ you can't be sure that you'll have time to try several languages so this might be more scalable within the time frame of the project and b/ most already trained models were trained for the English language.
2. Take a look at NLTK, the text library in Python. It might help a lot!

**Comment by QCTW** [comment]
Hi Ms. Haury,

Thanks for the note. As your suggests, we will take English tweets from 3 celebrities as Donlad Trump, Ivanka Trump (so that we can do a compare to see if in the same family they talk the same way), Ellen DeGeneres (To provide some positive energie to our robot)

**Comment by AnneClaireH** [comment]
Haha, yes positive energy will be needed, sounds great !
